routes/web.php
    Route::get("/cliente/destroy/{id}", ['as' => 'cliente.destroy', 'uses'=>'ClienteController@destroy']);
    Route::get("/cliente/proposta/{id}", ['as' => 'cliente.proposta', 'uses'=>'PropostaController@show']);
    Route::post("/cliente/proposta/submit", ['as' => 'cliente.proposta.submit', 'uses'=>'PropostaController@submit']);

    Route::get("/contato", ['as' => 'contato.index', 'uses'=>'ContatoController@index']);
    Route::get("/contato/create/{cliente_id}", ['as' => 'contato.create', 'uses'=>'ContatoController@create']);
    Route::get("/contato/edit/{id}", ['as' => 'contato.edit', 'uses'=>'ContatoController@edit']);
    Route::get("/contato/set/{id}", ['as' => 'contato.set', 'uses'=>'ContatoController@set']);
    Route::get("/contato/all/{id}", ['as' => 'contato.all', 'uses'=>'ContatoController@all']);
    Route::get("/contato/show/{id}", ['as' => 'contato.set', 'uses'=>'ContatoController@show']);
    Route::post("/contato/store", ['as' => 'contato.store', 'uses'=>'ContatoController@store']);
    Route::post("/contato/update/{id}", ['as' => 'contato.update', 'uses'=>'ContatoController@update']);
    Route::get("/contato/destroy/{id}", ['as' => 'contato.destroy', 'uses'=>'ContatoController@destroy']);

    Route::get("/endereco", ['as' => 'endereco.index', 'uses'=>'EnderecoController@index']);
    Route::get("/endereco/create/{cliente_id}", ['as' => 'endereco.create', 'uses'=>'EnderecoController@create']);
    Route::get("/endereco/edit/{id}", ['as' => 'endereco.edit', 'uses'=>'EnderecoController@edit']);
    Route::post("/endereco/store", ['as' => 'endereco.store', 'uses'=>'EnderecoController@store']);
    Route::post("/endereco/update/{id}", ['as' => 'endereco.update', 'uses'=>'EnderecoController@update']);
    Route::get("/endereco/destroy/{id}", ['as' => 'endereco.destroy', 'uses'=>'EnderecoController@destroy']);

    Route::get("/credenciamento", ['as' => 'credenciamento.index', 'uses'=>'CredenciamentoController@index']);
    Route::get("/credenciamento/create/{cliente_id}", ['as' => 'credenciamento.create', 'uses'=>'CredenciamentoController@create']);
    Route::get("/credenciamento/edit/{id}", ['as' => 'credenciamento.edit', 'uses'=>'CredenciamentoController@edit']);
    Route::post("/credenciamento/store", ['as' => 'credenciamento.store', 'uses'=>'CredenciamentoController@store']);
    Route::post("/credenciamento/update/{id}", ['as' => 'credenciamento.update', 'uses'=>'CredenciamentoController@update']);
    Route::get("/credenciamento/show/{id}", ['as' => 'credenciamento.show', 'uses'=>'CredenciamentoController@show']);

    Route::get("/visita", ['as' => 'visita.index', 'uses'=>'VisitaController@index']);
    Route::get("/visita/view/{id}", ['as' => 'visita.view', 'uses'=>'VisitaController@view']);
    Route::get("/visita/create/{cliente_id}", ['as' => 'visita.create', 'uses'=>'VisitaController@create']);
    Route::get("/visita/edit/{id}", ['as' => 'visita.edit', 'uses'=>'VisitaController@edit']);
    Route::post("/visita/store", ['as' => 'visita.store', 'uses'=>'VisitaController@store']);
    Route::post("/visita/reagendar", ['as' => 'visita.reagendar', 'uses'=>'VisitaController@reagendar']);
    Route::get("/visita/confirmar/{id}", ['as' => 'visita.confirmar', 'uses'=>'VisitaController@confirmar']);
    Route::post("/visita/cancelar", ['as' => 'visita.cancelar', 'uses'=>'VisitaController@cancelar']);
    Route::post("/visita/update/{id}", ['as' => 'visita.update', 'uses'=>'VisitaController@update']);
    Route::get("/visita/destroy/{id}", ['as' => 'visita.destroy', 'uses'=>'VisitaController@destroy']);
    Route::get("/visita/relatorio/{id}/{cliente}", ['as' => 'visita.relatorio', 'uses'=>'VisitaController@relatorio']);
    Route::post("/visita/submit/relatorio", ['as' => 'visita.submit.relatorio', 'uses'=>'VisitaController@submit']);
    Route::get("/visita/remove-participante/{id}", ['as' => 'visita.remove.participante', 'uses'=>'VisitaController@removeParticipante']);

    Route::get("/operacao", ['as' => 'operacao.index', 'uses'=>'OperacaoController@index']);
    Route::get("/operacao/create/{cliente_id}", ['as' => 'operacao.create', 'uses'=>'OperacaoController@create']);
    Route::get("/operacao/edit/{id}", ['as' => 'operacao.edit', 'uses'=>'OperacaoController@edit']);
    Route::post("/operacao/store", ['as' => 'operacao.store', 'uses'=>'OperacaoController@store']);
    Route::post("/operacao/update/{id}", ['as' => 'operacao.update', 'uses'=>'OperacaoController@update']);
    Route::get("/operacao/show/{id}", ['as' => 'operacao.show', 'uses'=>'OperacaoController@show']);
    Route::get("/operacao/destroy/{id}", ['as' => 'operacao.destroy', 'uses'=>'OperacaoController@destroy']);

    Route::get("/operacao/incoterm/{id}", ['as' => 'operacao.incoterm', 'uses'=>'OperacaoIncotermController@incoterm']);

    Route::get("/alfandega/cliente", ['as' => 'alfandega.cliente.index', 'uses'=>'ClienteAlfandegaController@index']);
    Route::get("/alfandega/cliente/create/{cliente_id}", ['as' => 'alfandega.cliente.create', 'uses'=>'ClienteAlfandegaController@create']);
    Route::get("/alfandega/cliente/edit/{id}", ['as' => 'alfandega.cliente.edit', 'uses'=>'ClienteAlfandegaController@edit']);
    Route::post("/alfandega/cliente/store", ['as' => 'alfandega.cliente.store', 'uses'=>'ClienteAlfandegaController@store']);
    Route::post("/alfandega/cliente/update/{id}", ['as' => 'alfandega.cliente.update', 'uses'=>'ClienteAlfandegaController@update']);
    Route::get("/alfandega/cliente/show/{id}", ['as' => 'alfandega.cliente.show', 'uses'=>'ClienteAlfandegaController@show']);
    Route::get("/alfandega/cliente/destroy/{id}", ['as' => 'alfandega.cliente.destroy', 'uses'=>'ClienteAlfandegaController@destroy']);

    Route::get("/perfil", ['as' => 'perfil.index', 'uses'=>'InformacaoPerfilController@index']);
    Route::get("/perfil/create/{cliente_id}", ['as' => 'perfil.create', 'uses'=>'InformacaoPerfilController@create']);
    Route::get("/perfil/edit/{id}", ['as' => 'perfil.edit', 'uses'=>'InformacaoPerfilController@edit']);
    Route::post("/perfil/store", ['as' => 'perfil.store', 'uses'=>'InformacaoPerfilController@store']);
    Route::post("/perfil/update/{id}", ['as' => 'perfil.update', 'uses'=>'InformacaoPerfilController@update']);
    Route::get("/perfil/show/{id}", ['as' => 'perfil.show', 'uses'=>'InformacaoPerfilController@show']);
    Route::get("/perfil/destroy/{id}", ['as' => 'perfil.destroy', 'uses'=>'InformacaoPerfilController@destroy']);

    Route::get("/ligacao", ['as' => 'ligacao.index', 'uses'=>'LigacaoController@index']);
    Route::get("/ligacao/create", ['as' => 'ligacao.create', 'uses'=>'LigacaoController@create']);
    Route::get("/ligacao/edit/{id}", ['as' => 'ligacao.edit', 'uses'=>'LigacaoController@edit']);
    Route::post("/ligacao/store", ['as' => 'ligacao.store', 'uses'=>'LigacaoController@store']);
    Route::post("/ligacao/update/{id}", ['as' => 'ligacao.update', 'uses'=>'LigacaoController@update']);
    Route::get("/ligacao/show/{id}", ['as' => 'ligacao.show', 'uses'=>'LigacaoController@show']);
    Route::get("/ligacao/destroy/{id}", ['as' => 'ligacao.destroy', 'uses'=>'LigacaoController@destroy']);

    Route::get("/contato/parceiro", ['as' => 'contato.parceiro.index', 'uses'=>'ContatoParceiroController@index']);
    Route::get("/contato/parceiro/create/{cliente_id}", ['as' => 'contato.parceiro.create', 'uses'=>'ContatoParceiroController@create']);
    Route::get("/contato/parceiro/edit/{id}", ['as' => 'contato.parceiro.edit', 'uses'=>'ContatoParceiroController@edit']);
    Route::post("/contato/parceiro/store", ['as' => 'contato.parceiro.store', 'uses'=>'ContatoParceiroController@store']);
    Route::post("/contato/parceiro/update/{id}", ['as' => 'contato.parceiro.update', 'uses'=>'ContatoParceiroController@update']);
    Route::get("/contato/parceiro/show/{id}", ['as' => 'contato.parceiro.show', 'uses'=>'ContatoParceiroController@show']);
    Route::get("/contato/parceiro/destroy/{id}", ['as' => 'contato.parceiro.destroy', 'uses'=>'ContatoParceiroController@destroy']);

    Route::get("/relatorio/cliente", ['as' => 'relatorio.cliente', 'uses'=>'RelatorioController@cliente']);
    Route::get("/relatorio/visita", ['as' => 'relatorio.visita', 'uses'=>'RelatorioController@visita']);
    Route::get("/relatorio/contato", ['as' => 'relatorio.contato', 'uses'=>'RelatorioController@contato']);
    Route::get("/relatorio/credenciamento", ['as' => 'relatorio.credenciamento', 'uses'=>'RelatorioController@credenciamento']);
    Route::get("/relatorio/ligacao", ['as' => 'relatorio.ligacao', 'uses'=>'RelatorioController@ligacao']);

    Route::post("table/cliente", ['as' => 'table.cliente', 'uses'=>'TableController@cliente']);
    Route::post("table/visita", ['as' => 'table.visita', 'uses'=>'TableController@visita']);
    Route::post("table/credenciamento", ['as' => 'table.credenciamento', 'uses'=>'TableController@credenciamento']);
    Route::post("table/contato", ['as' => 'table.contato', 'uses'=>'TableController@contato']);
    Route::post("table/ligacao", ['as' => 'table.ligacao', 'uses'=>'TableController@ligacao']);

    Route::get("/relatorio/cliente/excel/{id}/{status_par}/{param}", ['as' => 'relatorio.cliente.excel', 'uses'=>'RelatorioController@generateCliente']);
    Route::get("/relatorio/visita/excel/{id}/{status_par}/{param}", ['as' => 'relatorio.visita.excel', 'uses'=>'RelatorioController@generateVisita']);
    Route::get("/relatorio/contato/excel/{id}/{status_par}/{param}", ['as' => 'relatorio.contato.excel', 'uses'=>'RelatorioController@generateContato']);
    Route::get("/relatorio/credenciamento/excel/{id}/{param}", ['as' => 'relatorio.credenciamento.excel', 'uses'=>'RelatorioController@generateCredenciamento']);
    Route::get("/relatorio/ligacao/excel/{id}/{param}", ['as' => 'relatorio.ligacao.excel', 'uses'=>'RelatorioController@generateLigacao']);

app/Proposta.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Proposta extends Model
{
    protected $fillable = [
        'data_proposta',
        'is_enviado',
        'is_accept',
        'justificativa',
        'tipo_proposta',
        'path_url',
        'obs',
        'contato',
        'is_imported',
        'cliente_id',
        'contato_id',
        'tokenizer',
    ];

    public function getStatusAttribute()
    {

        switch($this->is_accept){
            case 1:
                return "<span class=\"label label-default\">Não enviada</span>";
                break;
            case 2:
                return "<span class=\"label label-success\">Aguardando cliente</span>";
                break;
            case 3:
                return "<span class=\"label label-primary\">Aceita pelo cliente</span>";
                break;
            case 4:
                return "<span class=\"label label-danger\">Negada pelo cliente</span>";
                break;
        }

    }

    public function getCreatedAtAttribute($date)
    {
        if(strpos('000', $date) || $date == null){
            return null;
        }

        $date = Carbon::createFromFormat('Y-m-d H:i:s', $date);
        return $date->format('d/m/Y');
    }
}

app/Http/Controllers/TableController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Session;

class TableController extends Controller
{
    public function cliente(Request $request)
    {
        $arr = [];
        $data = $request->all();

        $table = \App\TableRelCliente::where('user_id',Session::get('usuario_id'))->get();

        $field = $data['column'];
        $arr['column_'.$field] = ($data['state'] == 'true') ? 1 : 0;

        if($table->count() > 0){
            $table->first()->update($arr);
        } else {
            $arr['user_id'] = Session::get('usuario_id');
            \App\TableRelCliente::create($arr);
        }

        return;
    }

    public function visita(Request $request)
    {
        $arr = [];
        $data = $request->all();

        $table = \App\TableRelVisita::where('user_id',Session::get('usuario_id'))->get();

        $field = $data['column'];
        $arr['column_'.$field] = ($data['state'] == true) ? 1 : 0;

        if($table->count() > 0){
            $table->first()->update($arr);
        } else {
            $arr['user_id'] = Session::get('usuario_id');
            \App\TableRelVisita::create($arr);
        }

        return;
    }

    public function credenciamento(Request $request)
    {
        $arr = [];
        $data = $request->all();

        $table = \App\TableRelCredenciamento::where('user_id',Session::get('usuario_id'))->get();

        $field = $data['column'];
        $arr['column_'.$field] = ($data['state'] == 'true') ? 1 : 0;

        if($table->count() > 0){
            $table->first()->update($arr);
        } else {
            $arr['user_id'] = Session::get('usuario_id');
            \App\TableRelCredenciamento::create($arr);
        }

        return;
    }

    public function contato(Request $request)
    {
        $arr = [];
        $data = $request->all();

        $table = \App\TableRelContato::where('user_id',Session::get('usuario_id'))->get();

        $field = $data['column'];
        $arr['column_'.$field] = ($data['state'] == 'true') ? 1 : 0;

        if($table->count() > 0){
            $table->first()->update($arr);
        } else {
            $arr['user_id'] = Session::get('usuario_id');
            \App\TableRelContato::create($arr);
        }

        return;
    }

    public function ligacao(Request $request)
    {
        $arr = [];
        $data = $request->all();

        $table = \App\TableRelLigacao::where('user_id',Session::get('usuario_id'))->get();

        $field = $data['column'];
        $arr['column_'.$field] = ($data['state'] == 'true') ? 1 : 0;

        if($table->count() > 0){
            $table->first()->update($arr);
        } else {
            $arr['user_id'] = Session::get('usuario_id');
            \App\TableRelLigacao::create($arr);
        }

        return;
    }
}

resources/views/admin/cliente/view/table/alfandega.blade.php
<table id="datatable2" class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Descrição</th>
        <th>Contato</th>
        <th>Acordo</th>
        <th>Visita</th>
        <th class="col-sm-3">Ações</th>
    </tr>
    </thead>
    <tbody>
        @foreach($alfandegas as $alfandega)
            <tr>
                <td>{{ $alfandega->alfandega($alfandega->id) }}</td>
                <td>{{ $alfandega->contato }}</td>
                <td>{!!  ($alfandega->is_acordo == 1) ? '<i class="fa fa-check"></i>' : '<i class="fa fa-close"></i>'  !!}</td>
                <td>{!!  ($alfandega->is_visita == 1) ? '<i class="fa fa-check"></i>' : '<i class="fa fa-close"></i>'  !!}</td>
                <td class="col-sm-3">
{{--
                    <button data-id="{{ $alfandega->id }}" class="btn ink-reaction btn-floating-action btn-sm btn-primary operacao-show"><i class="fa fa-eye"></i></button>
--}}
                    <a href="{{ route('alfandega.cliente.edit', $alfandega->id) }}" class="btn ink-reaction btn-floating-action btn-sm btn-info"><i class="fa fa-edit"></i></a>
                    <a href="{{ route('alfandega.cliente.destroy', $alfandega->id) }}" class="btn ink-reaction btn-floating-action btn-sm btn-danger"><i class="fa fa-close"></i></a>
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

resources/views/admin/cliente/view/table/credenciamento.blade.php
<table id="datatable1" class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Item</th>
        <th class="hidden-xs">Vencimento</th>
        <th class="col-sm-3">Ações</th>
    </tr>
    </thead>
    <tbody>
        @foreach($credenciamentos as $credenciamento)
            <tr>
                <td>{{ $credenciamento->item->descricao }}</td>
                <td>{{ $credenciamento->vencimento }}</td>
                <td>
                    <a href="{{ route('credenciamento.edit', $credenciamento->id) }}" class="btn ink-reaction btn-floating-action btn-sm btn-info"><i class="fa fa-edit"></i></a>
                    <button data-id="{{ $credenciamento->id }}" class="btn ink-reaction btn-floating-action btn-sm btn-primary credenciamento-show"><i class="fa fa-eye"></i></button>
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

@include('admin.cliente.modal.credenciamento')

resources/views/admin/cliente/view/table/operacao.blade.php
<table style="margin-top:50px;" id="datatable5" class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Tipo de Operacao</th>
        <th class="hidden-xs">Marítmo</th>
        <th class="hidden-xs">Aéreo</th>
        <th class="hidden-xs">Rodoviário</th>
        <th class="hidden-xs">Previsao</th>
        <th class="col-sm-3">Ações</th>
    </tr>
    </thead>
    <tbody>
        @foreach($operacoes as $operacao)
            <tr>
                <td>{{ ($operacao->tipo_operacao == 1) ? 'Importação' : 'Exportação' }}</td>
                <td>{!! ($operacao->is_maritmo == 1) ? '<i class="fa fa-check"></i>' : '<i class="fa fa-close"></i>' !!}</td>
                <td>{!! ($operacao->is_aereo == 1) ? '<i class="fa fa-check"></i>' : '<i class="fa fa-close"></i>' !!}</td>
                <td>{!! ($operacao->is_rodoviario == 1) ? '<i class="fa fa-check"></i>' : '<i class="fa fa-close"></i>' !!}</td>
                <td>{{ $operacao->previsao }}</td>
                <td>
                    <button data-id="{{ $operacao->id }}" class="btn ink-reaction btn-floating-action btn-sm btn-primary operacao-show"><i class="fa fa-eye"></i></button>
                    <a href="{{ route('operacao.edit', $operacao->id) }}" class="btn ink-reaction btn-floating-action btn-sm btn-info"><i class="fa fa-edit"></i></a>
                    <a href="{{ route('operacao.destroy', $operacao->id) }}" class="btn ink-reaction btn-floating-action btn-sm btn-danger"><i class="fa fa-close"></i></a>

                </td>
            </tr>
        @endforeach
    </tbody>
</table>

@include('admin.cliente.modal.operacao')

resources/views/admin/cliente/view/table/proposta.blade.php
<table id="datatable3" class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Data da Proposta</th>
            <th class="hidden-xs">Status</th>
            <th class="col-sm-3">Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach($propostas as $proposta)
            <tr>
                <th>{{ $proposta->created_at }}</th>
                <th>{!!  $proposta->status  !!}</th>
                <th class="col-sm-3">
                    @if($proposta->is_enviado == 0 && $proposta->is_accept < 3)
                        <button type="button" data-id="{{ $proposta->id }}" data-toggle="modal" data-target="#" class="btn ink-reaction btn-floating-action btn-sm btn-info showdata"><i class="fa fa-eye"></i></button>
                        <button type="button" data-id="{{ $proposta->id }}" data-toggle="modal" data-target="#sendproposta" class="btn ink-reaction btn-floating-action btn-sm btn-success sendorder"><i class="fa fa-send"></i></button>
                    @else
                        <button type="button" data-id="{{ $proposta->id }}" data-toggle="modal" data-target="#" class="btn ink-reaction btn-floating-action btn-sm btn-info showdata"><i class="fa fa-eye"></i></button>
                    @endif
                </th>
            </tr>
        @endforeach
    </tbody>
</table>

<div class="modal fade" id="sendproposta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="form-send-contato" method="post" action="{{ route('proposta.send') }}">
                <input type="hidden" name="cliente_id" value="{{ $cliente->id }}">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Selecione o Contato</h4>
                </div>
                <div class="modal-body">
                    <div id="div-dados"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                    <button type="submit" id="send-form-proposta" class="btn btn-primary">Enviar Proposta</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="viewproposta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
    <div class="modal-dialog" role="document"style="width: 90%">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Dados da Proposta</h4>
            </div>
            <div class="modal-body">
                <div id="div-dados-proposta"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
            </div>

        </div>
    </div>
</div>

resources/views/admin/cliente/view/table/resumo.blade.php
<table id="datatable-servico" class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Operação</th>
        <th>Ano</th>
        <th>Mês</th>
        <th>Total</th>
        <th>Quantidade</th>
    </tr>
    </thead>
    <tbody>

        @if(!is_null($resumo_cliente))
            @foreach($resumo_cliente as $resumo)
                <tr>
                    <td>{{ $resumo['OPE_CODIGO'] }}</td>
                    <td>{{ $resumo['ANO'] }}</td>
                    <td>{{ $controller->getMonth($resumo['MES']) }}</td>
                    <td>{{ $resumo['VALOR'] }}</td>
                    <td>{{ $resumo['QUANTIDADE'] }}</td>
                </tr>
            @endforeach
        @endif
    </tbody>
</table>

resources/views/admin/cliente/view/table/visita.blade.php
<table id="datatable4" class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Data da Visita</th>
        <th class="hidden-xs">Status</th>
        <th class="col-sm-3">Ações</th>
    </tr>
    </thead>
    <tbody>
    @foreach($visitas as $visita)
    <tr class="gradeX" id="idVisita-">
        <td>{{ $visita->data }}</td>
        <td class="hidden-xs">{!! $visita->statusVisita !!}</td>
        <td>
            @if((strtotime ( $visita->data ) <= strtotime ( date('d/m/y') )) &&  ($visita->status == 1 || $visita->status == 4))
                <a href="{{ route('visita.edit', $visita->id) }}" class="btn ink-reaction btn-floating-action btn-sm btn-info"><i class="fa fa-edit"></i></a>
                <button data-id="{{ $visita->id }}" class="btn ink-reaction btn-floating-action btn-sm btn-warning remarcar"><i class="fa fa-rotate-right"></i></button>
                <a href="{{ route('visita.confirmar', $visita->id) }}" class="btn ink-reaction btn-floating-action btn-sm btn-success"><i class="fa fa-check"></i></a>
                <button data-id="{{ $visita->id }}" class="btn ink-reaction btn-floating-action btn-sm btn-danger cancelar"><i class="fa fa-close"></i></button>
                <button data-id="{{ $visita->id }}" class="btn ink-reaction btn-floating-action btn-sm btn-primary view-visita"><i class="fa fa-eye"></i></button>
            @elseif((strtotime ( $visita->data ) > strtotime ( date('d/m/y') )) && ($visita->status == 1 || $visita->status == 4))
                <a href="{{ route('visita.edit', $visita->id) }}" class="btn ink-reaction btn-floating-action btn-sm btn-info"><i class="fa fa-edit"></i></a>
                <a href="{{ route('visita.confirmar', $visita->id) }}" class="btn ink-reaction btn-floating-action btn-sm btn-success"><i class="fa fa-check"></i></a>
                <button data-id="{{ $visita->id }}" class="btn ink-reaction btn-floating-action btn-sm btn-danger cancelar"><i class="fa fa-close"></i></button>
                <button data-id="{{ $visita->id }}" class="btn ink-reaction btn-floating-action btn-sm btn-primary view-visita"><i class="fa fa-eye"></i></button>
            @elseif((strtotime ( $visita->data ) < strtotime ( date('d/m/y') )) && $visita->status == 2)
                <a href="{{ route('visita.relatorio', [$visita->id, $cliente->id]) }}" class="btn ink-reaction btn-floating-action btn-sm btn-success"><i class="fa fa-newspaper-o"></i></a>
                <button data-id="{{ $visita->id }}1" class="btn ink-reaction btn-floating-action btn-sm btn-primary view-visita"><i class="fa fa-eye"></i></button>
            @elseif((strtotime ( $visita->data ) < strtotime ( date('d/m/y') )) && $visita->status >= 6)
                <button data-id="{{ $visita->id }}" class="btn ink-reaction btn-floating-action btn-sm btn-primary view-visita"><i class="fa fa-eye"></i></button>
            @else
                <button data-id="{{ $visita->id }}" class="btn ink-reaction btn-floating-action btn-sm btn-warning remarcar"><i class="fa fa-rotate-right"></i></button>
            @endif
        </td>
    </tr>
    @endforeach
    </tbody>
</table>

@include('admin.cliente.modal.modal')